# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJdFqAzDpqCIKlcxP78IyQtLFexZ7eDj
"""

!pip install streamlit

!pip install streamlit
!pip install scipy pandas

!streamlit run app.py & npx localtunnel --port 8501